name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'v{major}.{minor}.{patch}-{beta/alpha}'
        # Default value if no value is explicitly provided
        default: 'v1.0.0-alpha'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build --if-present
      - name: zip dist folder
        run: zip -r dist.zip dist
      - name: file list
        run: ls
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT }}
          file: dist.zip
          asset_name: dist.zip
          tag: ${{ inputs.name }}
          overwrite: true
          
